F13::^v
F14::^c
F15::^d
F16::^+d
+^a::Send,and{Space}
+^b::Send,if{Space}__name__{Space}=={Space}'__main__':
+^c::Send,class
+#c::Send,chrome
+#d::Send,def{Space}
+^e::Send,else
+#e::Send,except
+^f::Send,for{Space}
+#f::Send,from{Space}import{Space}
^#f::Send,False
+^g::Send,get
+^h::Send,html
+#h::Send,href
+^i::Send,import{Space}
+#i::Send,items
+^j::Send,join
+#k::Send,key
+^l::Send,lxml
+^m::Send,is{Space}
+^n::Send,not{Space}
+#n::Send,None
^#n::Send,name
+^o::Send,open
+^p::Send,print
+#p::Send,python
^#p::Send,path
+^q::Send,queue
+^r::Send,return{Space}
+#r::Send,requests
^#r::Send,range
+^s::Send,self
+^t::Send,try:
+#t::Send,text
^#t::Send,True
+^u::Send,url
+#u::Send,umihico
+^v::Send,value
+^w::Send,with
+#w::Send,windows
+^x::Send,xpath
+^y::Send,yield
+#y::Send,you
+^z::Send,zip
